#端口号
server:
  port: 8887
#数据库
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/tradesystem?characterEncoding=utf8&&useSSL=false&&serverTimezone=UTC&&rewriteBatchedStatements=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.gem.tradesystem.back.entity,com.gem.tradesystem.entity
logging:
  level:
    com.gem.tradesystem.mapper: debug

#七牛云-有效期3-23
upload:
  qiniu:
    domain: http://q638natxm.bkt.clouddn.com
    access-key: iuurc9l3zpW5qEIn_yU4BC-3nqx8xiTZ7XOF7uQI
    secret-key: 14Wik517ZD7FpIBrdXLR-vtlCvNmP1rTLg0zdtP5
    bucket: themebox
qi:
  domain: http://q6rklxhce.bkt.clouddn.com
  accessKey: iuurc9l3zpW5qEIn_yU4BC-3nqx8xiTZ7XOF7uQI
  secretKey: 14Wik517ZD7FpIBrdXLR-vtlCvNmP1rTLg0zdtP5
  bucket: picuploading

#mybatis plus配置
mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath*:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.gem.tradesystem.back.entity,com.gem.tradesystem.entity

  #设置id自增长的模式
  global-config:
    db-config:
      id-type: auto

    #    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 0
    #    #驼峰下划线转换
    #    db-column-underline: true
    #    #mp2.3+ 全局表前缀 mp_
    #    #table-prefix: mp_
    #    #刷新mapper 调试神器
    #    #refresh-mapper: true
    #    #数据库大写下划线转换
    #    #capital-mode: true
    #    # Sequence序列接口实现类配置
    #    key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #    #逻辑删除配置（下面3个配置）
    logic-delete-value: 1
    logic-not-delete-value: 0
  #    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  #    #自定义填充策略接口实现
  #    meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #    #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    #    map-underscore-to-camel-case: true
    cache-enabled: true
#    #配置JdbcTypeForNull, oracle数据库必须配置
#    jdbc-type-for-null: 'null'